# Generated by Django 6.0.5 on 2026-05-25 16:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel Export'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel API/CSV')], max_length=50)),
                ('ingestion_method', models.CharField(choices=[('CSV', 'CSV Upload'), ('API', 'API Integration'), ('JSON', 'JSON Upload')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel Export'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel API/CSV')], max_length=50)),
                ('raw_column', models.CharField(max_length=255)),
                ('mapped_field', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('source_type', 'raw_column')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=10)),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit', models.CharField(max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('calculated_emission', models.DecimalField(decimal_places=4, max_digits=19)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VALIDATED', 'Validated (System)'), ('FLAGGED', 'Flagged for Suspicion'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked (Immutable)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('suspicious_flag', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.company')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=50)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.emissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_uploads', to='core.company')),
                ('data_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datasource')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_stage', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='core.rawupload')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmissionRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('category', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=10)),
                ('activity_type', models.CharField(max_length=100)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unit', models.CharField(max_length=20)),
                ('emission_factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('calculated_emission', models.DecimalField(decimal_places=4, max_digits=19)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VALIDATED', 'Validated (System)'), ('FLAGGED', 'Flagged for Suspicion'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked (Immutable)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('suspicious_flag', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.datasource')),
                ('raw_upload', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.rawupload')),
            ],
            options={
                'verbose_name': 'historical emission record',
                'verbose_name_plural': 'historical emission records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.rawupload'),
        ),
    ]
